### ISSUE TITLE
Why Vagrant & Virtualbox?

### ISSUE THREAD

**Issue by picoroma** [aws-samples/aws-install-sap-with-jenkins-ansible#13]
WHY:
For running this project you have to have installed the following software on your local computer

- Vagrant - https://www.vagrantup.com/
- Oracle VirtualBox - https://www.virtualbox.org/

?
Is not possible to use other EC2 instances on AWS - for example ?
THX

**Comment by guisesterheim** [comment]
Hi Picoroma!

This is required because we're using a Virtual Machine (virtualbox) to create the local Jenkins that will orchestrate all the process. For now this is an important part of the solution.

If you feel comfortable, you can also run Terraform and Ansible manually to get rid of Jenkins. This will give you more steps to accomplish, but will reach the same output.

Thanks!

**Comment by picoroma** [comment]
@guisesterheim : Are you available for a short call to explain a little bit   the project:
https://github.com/aws-samples/terraform-aws-sap-netweaver-on-hana
I saw that you are contribuiting on It.
If YES, Can you write me an email to pico_@_cocco.biz ?

**Comment by guisesterheim** [comment]
Hi Picoroma!

Yes, that will be great. Please reach out to your AWS Account Manager and ask them to loop me in the discussion.

Thanks!

**Comment by guisesterheim** [comment]
I'm closing this issue now, waiting for our conversation. Thanks!
